### PR TITLE
Added support for sharing images

### PR DESCRIPTION
**Pull request by denvers**
I've added support for sharing images into a React Native app. 

Howto:
* Add intent-filter for images into activity:

```
<intent-filter>
  <action android:name="android.intent.action.SEND" />
  <category android:name="android.intent.category.DEFAULT" />
  <data android:mimeType="image/*" />
</intent-filter>
```

* Add support in your React Native app to catch the shared image from outside your app and process him:

```
componentWillMount() {
  var that = this;
  ShareMenu.getSharedText((text :string) => {

    if (text && text.length) {

      if (text.startsWith('content://media/')) {

        // `text` contains the local file URL to the shared image

      } else {

        // `text` contains another string (probably text)

      }
  })
}
```

### CODE REVIEW

**Comment by mantou132** [comment]
The image URL is the absolute path?

**Comment by mantou132** [comment]
support multiple images?

https://developer.android.com/training/sharing/receive.html

**Comment by isaachinman** [comment]
Hi @mantou132 does this PR fully support multi images? Are you/anyone using this in production?

If `react-native-share-menu` is not stable enough yet, how do we do this manually?

**Comment by mantou132** [comment]
@infojunkie 

I am using myself. https://play.google.com/store/apps/details?id=com.impress_rn
package.json : http://upzip.b0.upaiyun.com/impress_webview/package.json

However, there is a little change. https://github.com/mantou132/react-native-share-menu/commit/5db5dd6ed34cd64b9db1e078e209f51cec319f24

**Comment by isaachinman** [comment]
@mantou132 Okay, so you are using your fork in production? Is this cross platform or just Android? It supports multi-image sharing on both platforms?

**Comment by mantou132** [comment]
@isaachinman yes.
only support Android.

**Comment by caiosba** [comment]
Hey guys, I'm going to review it very soon.

**Comment by caiosba** [comment]
Thanks for your contribution! I merged that into `master` and released a new version of the module.

**Pull request merged**
