### PR TITLE
Allow multiple items

### PR DESCRIPTION
**Pull request by flogy**
Allow sharing multiple items at once.

There already are various PRs for this. As they are no longer in sync with the latest version, I've created this new one which is based on https://github.com/meedan/react-native-share-menu/pull/119 --> props go out to @vstoyanoff 🎉

**How to use this feature in your project NOW:**
If you want to use this, run `npm i -S flogy/react-native-share-menu#feat/multiple-attachments` which will install the dependency from the GitHub repository behind this PR instead of NPM! Make sure to revert back to the official dependency once this PR was merged.

In case there are any issues / it gets out of sync with newer versions of the official dependency, don't hesitate to open up an issue here: https://github.com/flogy/react-native-share-menu

**Fixes:**
https://github.com/meedan/react-native-share-menu/issues/77

**Duplicates:**
https://github.com/meedan/react-native-share-menu/pull/130
https://github.com/meedan/react-native-share-menu/pull/119

### CODE REVIEW

**Comment by flogy** [comment]
Nice additions to this PR would be:
- Update example code.
- Update docs, especially where the file limits are set to `1` which must be changed to e.g. `100` to get this PR to work.
- Update TypeScript types to line up with this PR and thus receive an item array.

**Comment by vstoyanoff** [comment]
🙌

**Comment by eranga-akva** [comment]
This is much needed. 💯

**Comment by slopez93** [comment]
Please merge it ! Thanks @flogy 🚀

**Comment by TatuUlmanen** [comment]
Any idea when this will be merged?

**Comment by kristi-gjeka** [comment]
Please merge this! It works perfectly during my testing, and it would be beneficial to many

**Comment by caiosba** [comment]
Thanks a lot! BTW I'm looking for co-maintainers of this module, specially for iOS stuff :)

**Pull request merged**
