### PR TITLE
Feat/listeners

### LINKED ISSUE #4: How to render share UI only when dispatched by iOS Share Action and AndroidIntent?
Hi, bit of a beginner here in RN, iOS and Android dev. The example code works quite well to demonstrate how the code behaves when the host app invokes the sharing action.

However, when loading the example app directly, index.ios.js and index.android.js will render an error because no sharing link/url has been passed to the app when NativeModules.ShareMenuModule.getSharedText is invoked inside componentWillMount.

In a real-world app, index.js would load the main app view and only when a sharing action is invoked by the host app and sent to the app would NativeModules.ShareMenuModule.getSharedText be invoked.

Any recommendations on how to accomplish this so NativeModules.ShareMenuModule.getSharedText is only invoked when sent to the app via the host app's sharing action?  I know this isn't really a question specifically about the module, but if you were even to just link me over to some resources explaining how to do this, that would suffice.  Being a n00b, I'm having a problem googling the right keywords to find a resource or tutorial to help learn this.

Thanks!
[PS, I wanted to post this to meedan/react-native-share-menu but there is no Issues tab so I posted here]

### LINKED ISSUE #39: Sharing creates new instances AND single instance app not receiving shared URL
My issue is a combination of:
https://github.com/meedan/react-native-share-menu/issues/18
and
https://github.com/meedan/react-native-share-menu/issues/25

Running:
react-native: 0.59.9
react: 16.8.3
react-native-share-menu: 2.2.2

When I set:
```android:launchMode="singleTop"```

My app receives Shared URLs while the app is already running (desired effect), but it ends up creating multiple instances of my app (undesired effect). 

When I set the ```launchMode``` to ```"singleTask"``` or ```"singleInstance"```, my app does not receive Shared URLS while the app is already running (undesired effect), but also doesn't create multiple instances (desired effect). This is the case even when ShareMenu.getSharedText (see below) is in an AppState listener. 

Setting 
```android:documentLaunchMode="never"```

Also prevents my app from receiving Shared URLs while the app is currently running (undesired effect).

Is there a workaround for this? An alternative solution? 
```
componentWillMount() {
        AppState.addEventListener('change', this._handleAppStateChange);
}
_handleAppStateChange = (nextAppState) => {
        if (
          this.state.appState.match(/inactive|background/) &&
          nextAppState === 'active'
        ) {
            if(Platform.OS === 'android') {   
                ShareMenu.getSharedText((text) => {
                    if (text && text.length) {
                        if(text !== this.props.activeTab.site.url) {
                            this.setSite(text);
                        }
                    }
                })
            }
        }
        this.setState({appState: nextAppState});
};
```

### LINKED ISSUE #48: Move to Listeners
Moving the package to listeners would make sharing work even if the app is already running on the background. This can have a common JS API for both Android and iOS

### PR DESCRIPTION
**Pull request by Gustash**
Fixes #4
Fixes #39
Fixes #48 

This PR adds listener support for both iOS and Android. The listener will get called if the app is already running in the background.

Due to this change, I went ahead and marked `getSharedText` as deprecated and added a new method called `getInitialShare`, which is more descriptive of its intended use. `getSharedText` simply calls `getInitialShare` for backwards compatibility.

It also ensures that the returned text is never `null` or `undefined`, it will always be a `string` and defaults to an empty `string`.

I've also updated the README instructions to reflect this, and merged the JS API for Android and iOS into a single `index.js`.

### CODE REVIEW

**Review by caiosba — APPROVED** [review]
Thanks, looks good to me. I tested on Android and works fine. Also, thanks for converting to React Hooks.

**Comment by Gustash** [comment]
> Thanks, looks good to me. I tested on Android and works fine. Also, thanks for converting to React Hooks.

No problem, it's what all the "cool kids" are using anyway haha

**Comment by Gustash** [comment]
@caiosba are you going to be releasing this to NPM btw?

**Comment by caiosba** [comment]
> @caiosba are you going to be releasing this to NPM btw?

Yes, released in v3.1.0.

**Pull request merged**
