### PR TITLE
iOS Rewrite

### PR DESCRIPTION
**Pull request by Gustash**
DONE:

- [x] Auto-linking support

- [x]  Text sharing support

- [x]  URL sharing support

- [x]  Image sharing support

- [x]  Update documentation

Would be nice to discuss a roadmap since I feel like this package could do a lot more on both iOS and Android.

### CODE REVIEW

**Comment by caiosba** [comment]
Looks good so far! We can discuss next steps after and iOS version and Android version are in sync.

**Comment by caiosba** [comment]
Thanks!!

**Comment by Gustash** [comment]
@caiosba feel free to review. I've updated the documentation, the rewrite keeps the same JS API as Android, and supports text, urls and images.

**Comment by Gustash** [comment]
You should probably release this as a major version update btw

**Review by caiosba — APPROVED** [review]

**Comment by Gustash** [comment]
@caiosba let me know when you plan to release this to NPM so I can go through the iOS issues and close the ones that are no longer relevant.

Also, let me know how you want to address a roadmap. Like I said, I have a few ideas, so I could open an issue with them so we can all discuss them.

**Comment by caiosba** [comment]
Thanks, I merged and released a new version. I assigned you to a couple remaining iOS issues, please take a look. Feel free to open new tickets for feature ideas and label them with the "feature" label, we already have a few.

**Pull request merged**
