### PR TITLE
Separate JS bundle for Share Extension React View

### LINKED ISSUE #64: Cannot get the Custom IOS Share View to work
Followed the instructions, but when Click my app from the share menu, an  white modal slides up from the bottom for a split second and then closes. Works fine without the Custom IOS Share View and the example works fine for me locally.  Not getting any errors, so not sure where or how to debug this.  Any help/pointers would be appreciated.

### PR DESCRIPTION
**Pull request by Gustash**
Fixes #64.

Needs #63 to be merged first.

This introduces a breaking change. Before, the JS bundle was shared between the main app and the app extension. This causes issues around the bundle size and memory footprint of the extension, as it most likely doesn't need everything the main app is shipping in terms of both JS and libraries.

Instead of supporting a case where people can either share a JS bundle, or have a separate one, I believe the cases where you would want a shared bundle are pretty much non-existant, and even then they would be heavily discouraged.

I recommend making a GitHub release when this is released on NPM telling people that to migrate from 4.x to 5.x they would need to:

- Add `export ENTRY_FILE=index.share.js` under `export NODE_BINARY=node` on the Share Extension's `Bundle React Native code and images` Build Phase.
- Move the AppRegistry's share component registration out from `index.js` into a new `index.share.js` file.

### CODE REVIEW

**Review by caiosba — CHANGES_REQUESTED** [review]
Can you please resolve the conflicts?

**Comment by Gustash** [comment]
@caiosba fixed

**Comment by caiosba** [comment]
Done! Released new version with instructions. Thanks!

**Comment by jonsherrard** [comment]
How does metro know to bundle two separate entry points?

**Comment by jesusbmx** [comment]
```sh
set -e

export ENTRY_FILE=index.share.js

# Script that is responsible for loading the "NODE_BINARY" variable
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"

# Script that is responsible for packaging the code and image assets of the React Native application
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

**Pull request merged**
